{% set version = "0.9.0" %}
{% set name = "fsspec" %}
{% set sha256 = "3f7a62547e425b0b336a6ac2c2e6c6ac824648725bc8391af84bb510a63d1a56" %}

package:
  name: fsspec
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-Make-metadata-dep-an-exrta.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }}  -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.5
    - pip
    - jinja2
  run:
    - python >=3.5

test:
  imports:
    - fsspec

about:
  home: https://github.com/intake/filesystem_spec
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A specification for pythonic filesystems
  dev_url: https://github.com/intake/filesystem_spec
  doc_url: https://filesystem-spec.readthedocs.io

extra:
  recipe-maintainers:
    - martindurant
    - TomAugspurger
